name: macOS build

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: brew install protobuf
    - name: make
      run: make mac
