name: Windows build (MXE)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install MXE dependencies
      run: |
        pwd
        sudo apt -y install \
        autoconf \
        automake \
        autopoint \
        bash \
        bison \
        bzip2 \
        flex \
        g++ \
        g++-multilib \
        gettext \
        git \
        gperf \
        intltool \
        libc6-dev-i386 \
        libgdk-pixbuf2.0-dev \
        libltdl-dev \
        libssl-dev \
        libtool-bin \
        libxml-parser-perl \
        lzip \
        make \
        openssl \
        p7zip-full \
        patch \
        perl \
        pkg-config \
        python \
        ruby \
        sed \
        unzip \
        wget \
        xz-utils
    - name: install MXE
      run: |
        git clone https://github.com/mxe/mxe.git
        cd mxe
        make cc protobuf
        export PATH=$(pwd)/usr/bin:$PATH
        export MXE_PROTOC=$(pwd)/usr/x86_64-pc-linux-gnu/bin/protoc
        pwd
    - name: make
      run: |
        cd ..
        make windows
