name: Windows build (MXE)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install MXE
      run: |
        git clone https://github.com/mxe/mxe.git
        cd mxe
        make cc protobuf
        export PATH=$(pwd)/usr/bin:$PATH
        export MXE_PROTOC=$(pwd)/usr/x86_64-pc-linux-gnu/bin/protoc
        pwd
    - name: make
      run: |
        cd ..
        make windows
